---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-scanner
resources:
  - network_policy.yaml
  - service.yaml
  - stateful_set.yaml
labels:
  - pairs:
      app.kubernetes.io/name: trivy
      app.kubernetes.io/component: server
    includeSelectors: true
configMapGenerator:
  - name: trivy-server-config
    literals:
      - LISTEN=0.0.0.0:4954
      - CACHE_DIR=/home/scanner/.cache/trivy
      # Approximately 6 months
      - CACHE_TTL=4320h
      - DB_REPOSITORY=ghcr.io/aquasecurity/trivy-db
