# permissions for end users to edit containerimagescans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: containerimagescan-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: image-scanner-operator
    app.kubernetes.io/part-of: image-scanner-operator
    app.kubernetes.io/managed-by: kustomize
  name: containerimagescan-editor-role
rules:
  - apiGroups:
      - stas.statnett.no
    resources:
      - containerimagescans
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - stas.statnett.no
    resources:
      - containerimagescans/status
    verbs:
      - get
