apiVersion: stas.statnett.no/v1alpha1
kind: ContainerImageScan
metadata:
  labels:
    app.kubernetes.io/name: containerimagescan
    app.kubernetes.io/instance: containerimagescan-sample
    app.kubernetes.io/part-of: kb-v4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kb-v4
  name: containerimagescan-sample
spec:
  # TODO(user): Add fields here
